CREATE TABLE professeur (
    numprof NUMBER(3) CONSTRAINT pk_professeur PRIMARY KEY,
    nom VARCHAR2(30) NOT NULL CHECK (nom = UPPER(nom)),
    prenom VARCHAR2(30) NOT NULL CHECK (prenom = INITCAP(prenom)),
    datenais DATE NOT NULL CHECK (datenais > TO_DATE('1900-01-01', 'YYYY-MM-DD')),
    ttal NUMBER(5) NOT NULL CHECK (ttal >= 0)
);

CREATE TABLE MATIERE (
    NUMMAT NUMBER(3) CONSTRAINT MATIERE_PK PRIMARY KEY,
    LIBELLE VARCHAR2(30) NOT NULL,
    COEF NUMBER(1) NOT NULL
);

CREATE TABLE ENSEIGNE (
    NUMPROF NUMBER(3),
    NUMMAT NUMBER(3),
    PROMO VARCHAR2(2),
    NBH NUMBER(3) CHECK (NBH IS NOT NULL AND NBH > 0),
    CONSTRAINT enseigne_pk PRIMARY KEY (NUMPROF, NUMMAT, PROMO)
);


CREATE TABLE RECAP (
    NUMPROF NUMBER(2),
    PROMO VARCHAR2(2),
    TOTALH NUMBER(4) CHECK (TOTALH IS NOT NULL AND TOTALH > 0),
    CONSTRAINT recap_pk PRIMARY KEY (NUMPROF, PROMO)
);

